---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-db-credentials
  namespace: app
spec:
  encryptedData:
    DATABASE_URL: AgBjWMzhiE66DyB2ctuonzO8jxVfujLa3HoLyx+fRcyGX1m+mdHHV7Ft+K6WLmUvKny6sq5AZsl3dGYMU0NJOuXPblLFESnOui2rDTJ7sd40nlrAaJR3Yb36TqYzuiqT95b2oFcFbOxG7ucWE9WWs+iacJJF7y9bG587utfqrxxAL/9T7M174nHXOR9+DYIy1ibIMsnsGmfHhpkSXJMuAryD2vC3lmzFsJ5fTvxJaytvwxGw1ZREPnSQ6xlopxVALRccme4N69sCjdT8KcoewLp1qExmmMRL6U/WhrS/p5rWW4Z2XsixNCJGzHjrxouz/yvDuoxACx/vdgBX4EPXD4fP1zpLmOCSJpji9NJgZmHsdy/8iVlatUqwsiRP/QRfTE7IAAznWynlhnt94wIo4Vmc6SJPNhvuKsKnZfQwgLQniLJ364ax+F91SMrutXOqinCMpzjDLepjwN59CQp9XZeklBqMmcnRSrm7X/qyxAgJOsckOuaLJwjCBfcxuKaIz2rIfztNwZOtv7NPD+5M6QKpcFCqQPwKAWgREiPwJILMi7HhwPxGn6d5akdnCuAHmtiCxbWzIPTWgfTSIszoSLFOnfTSTG013Zgl1IFsDI9bFy5+Bi4L/TTVBXSuWbn8L0vZoftUCvik7SA92PTH2aLEoLFVJIEDV9UUaUBkDqym/Wa9/sE0rI/lnoj2h+PVyqAYx6mnI+np3CmMCdGsNdEzrYPpUJmGbuS7jk8RxiSyUCsXyfssqZsAbVlLuDJQlD8vemVsouSqoVweX7TpB7xkIw8JX2AJAQY0A+DZGMfgSzhBSBlQOovc9F4U60bqRzPE8uiKMJ+noE6USzWs7g==
  template:
    metadata:
      name: api-db-credentials
      namespace: app
