---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-db-credentials
  namespace: app
spec:
  encryptedData:
    DATABASE_URL: AgCEq1AC6ulDeWbpYwdEzaxx44+PbOflqjHtn6Z21p91PKRVTEKI+vLnXLhWhcAOfIhM1gsKeDARuDFVqi84ZcFO5W7ptj36h+uSI3EyIV2Bj+RHFpGGr88LJrCHBARCZTLgA2vLEKrYP5JqJvTM9VkD6aMzhrDw7zINnZujPNtezDBf4zxFUi7C3ZdLA4qEquaPFCHHAqFAjQNj20us+fYADpkzHA4P9K9gAccIn1YdtDNud8OXUNc7gHZ2FqnWowE45vyCb5ZcbDJCqQhmhvJxbVecE2FTdnLtuaMT4nCzIZteNbfe642mxqslGQjKnfpu6Lg07Hi+CZOwj+7HXbmJAablYgXUru2wmFU1muoNwq1SAabDZTWYN5cdv2RKw0TDRvPITMULSJohpeYOpMGoC7oTfLVn9Dfjq+yCpl0bfLHxqEKdukqPaxXM9DYwQACbKe1f4uWuweVpnDVr/cIZqiCQdj3z87zJkX7yEIKnfBuZQVhn/A6pG8jafkL29SusqJPHiRBrej9iXlCwyCw+1w5dGfF5Ho7KI8e6yXc1UzCMz/XwrRCcvsV77Fb17FWQb3vNWMaADgN6w0ghWv/QQabnp2Y/X29rwN8q0O6wBjtJAKzcunw43bXqQ6HHtmrcQJBKMFb2mf2W0Adrgc6dwIJIqCSA9JOCQ7MNk55CMZhBY5i1+MUt/Kzxpg8+ZrgsdWO3Qe+psv4LmPegnJcqY+9NI89JyMuOc8w/Rg97chsGQqUIy0MIUjw31CCefXShiu4QVwTMKiWi+TeBGuZIzOktnvebtAIYpmpz22Oi9Av3ApU1aPnw8VlwD9KgxR3PZeLEVlQMbwmuEaNykpcAX6uulrNWwLFrjHMrWEJGH816I+rirxjmYTgXY2VBPiGq109kq8Y=
  template:
    metadata:
      name: api-db-credentials
      namespace: app
