---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-db-credentials
  namespace: app
spec:
  encryptedData:
    DATABASE_URL: AgAGzOJfayROhGsrlXveUMya3wa0zNPYB+kyJo9Sd2nyv91UhPW58+4HWlT9R48k1SnYt0Ui1PIQDekCgWylJPTh7FYFej089aJaLGre5OekCz97w6XNYcSm1gpEwRnF2Tb4nMSysdpLLTWr6VGW9cWpTG/mVcE2utVo7O9FqSx633U0hJkeTE80khS/a3rqO7mTw0hYHRo4vmXra4rcjVk73HpuDazFFJpsb7JzTus5oOIbXvfMS0v84EM2w/SHr1VK10jxAxxPCSQZvZGklz8LfFLqH6YA6XdtPfrVgUAn95xHgmCmrnSg9sDyrNAYd+JdzSiTAR4Lzbl0zdmO7WsqO5Abqpq0VKUNkPZSHRJ2KK1czWcHsJmbs9bPA+HKcixv0lyK+VvqKAgUXwO83JztfCUPW8VV7JN+SLilm3FUxIYKhSIbAM+hAgz5NQRI8aa+L2VzLaz3HlWB8ZXQHMJkjfxOHGQKxOik1lyhxCdGBLbBP6yIjpdRTH9BXz1VZ+QotTrmlKjaPopjtII9426jtJoxGGaIsIunJHBXWPk6euUCeMp3KqpFmlWU97a0h8Cvgl3cDG2KBSJes88ddvuLQWjqwUFVbUdBA4SWn2OLD231r1BMn0AiCyZWdXOyifpZOQvcIQTop20VzbfJ1FDy6BpVV3b9qLDzn7qkxYGiy/zQayo6aIH1aH05zu7htUJQtq9NZM0c70g3/5EtRK7kKbyYbLW4pAR0V3gYyz71zh3hdcfTrvwFgjY37TVTWMFL8HXjGt7z71nYu7qplFArlIXWGhT5HRY6zxf5eZwu9o08lf+3rDKBXv4FcyuB62CApVTn+gQMPlb7Kw==
  template:
    metadata:
      name: api-db-credentials
      namespace: app
