apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: app
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql@sha256:99be063781d171d3971089b49c992706bdab9ccbd2b57cdf126c7542773aedfe

  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      secret:
        name: postgres-owner-credentials

  storage:
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  backup:
    retentionPolicy: "7d"
    barmanObjectStore:
      destinationPath: s3://postgres-backups/postgres-cluster
      endpointURL: http://minio.app.svc.cluster.local:9000
      s3Credentials:
        accessKeyId:
          name: minio-credentials
          key: MINIO_ROOT_USER
        secretAccessKey:
          name: minio-credentials
          key: MINIO_ROOT_PASSWORD
      wal:
        compression: gzip
      data:
        compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-nightly
  namespace: app
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: postgres
