---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-owner-credentials
  namespace: app
spec:
  encryptedData:
    password: AgAn05UNOOf47H87XlcnTURK5umvhAcmtwGY/XKZkwclpkFEW99HF+b2fwjrvFQMusTsZf2ds93o3BKTDL55FN58Rn1Nv1CnLP+s3/CgsSHMSstNCXHEKR4aBFWxWfD58zWLArUmkiJ5UlzYKOJxKmzVL7ROJEa9+SvQZBuJ5i7MbY/1Alj5MKfond6c05rmWghRHl4IXx7mxuXVcGJ7GCTTKaZ/3xMTZ1TgTK2D4Psw8RvOAC4GHc6ocUceneMkfXguWJPa9NOnu94md7p5rgO0/vg3PCcI/ZjCCQJjjsXYik66aP11zqmSi6IM+pZ940pKlof/s2fNUs6wFtAQHr+k5am9hoxjnkXPxw9f5kLqDoOWu25xIa5jQSumkiH5kPTYk7qBneCbBkA//UTdF5mM0VKM8DuM3GXOHI36t3HaaP21iZq9PKmH981BGjR3qgFUNHvquC5pxEGGQgDERdd0TgSmgRebV6KUEAhql6Svia9komexEYfNthc63s/Kh12ib1ejLCR3VyZQRWtY0ICDw8SwdAQjQgXhwbXb26Mn1ZKcpgaM1dChSK42xPOTDP9K7Ye4ERjpxBktZ0W2BE2VpYKC4kUJuWxUwY7TQW7CWs935WCygpON6c5NthkiFNKsljbfG91CTmiLQRSTIha3sxNUQJtIN5ailtJ/I+I48+am+nR/G9jaoysAUkVSh7jrjugQB5tsQI68JIso2gXTbVvv8spuVUb1/m/ZZ9E=
    username: AgBvFjAXVwd/tlQKKerCtLV7Xsm4FnLz2G+7Ez31maVSLZjLOPkGFsqFEhevwGlAitAGZJp1ecbu+wDxuJZwOp0ROwSWRNDBCC9oux+/Ju0d3t8LRh5DS9WXoj2vp9AHiUuNbSKGQVbuwYa8M+DfmgpXtKsWxU+NugJl04OoL/KLlogR1Dx9M25/FY4phpvElU6LSK3nnyO0j8AzroQyE8n5lWadyonmAzZY291HuzjoSexejFSHrVYMaZk/TebKu2jT71GuwmRmH6uBU8PSlr1E5SxLA/NyzKLKpLa8kzE2l5c2An2Jybr0M6qtWOr/vR12jsrwg40vPUZat3xJ/qAWvZzrf3MDoLOejwYI8PIGIRefEa++xEhhJZOEarSjSV06lWMTHRWaTHGf7HFztnTBTUJU3nnXR79aqyReSYMl4yspr43mOvAuejEVfoE1WSWcMic8CalywnX2RZWCHp9dg0PwzmWVOUIODGmwqmSgBa/79SPj2vVNJF6aBNZM+aHtKzwAHRxgSCvDDxw30ZgrM9Psc4S6sGByOeTZYYi+8Jlh2t2z9IKwelNJD1QiErymb3EVgTLdztEU17A3ZBmL1oUbza3uoWDeENrXKBshY6AJQ+r/Kr/Rg73Dz8lxGE61KpKDpw7ZpNU1xSA3OF9dtQCFpMolp5yKHZZO0XYyJ5yrmGoGufd5fEXUNB62G96mTQ/HSPwA
  template:
    metadata:
      name: postgres-owner-credentials
      namespace: app
    type: kubernetes.io/basic-auth
