apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/hargeghamm/gitops-minikube-platform.git
    targetRevision: main
    path: manifests/namespace
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
