apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-minio
  namespace: app
spec:
  podSelector:
    matchLabels:
      app: minio
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              cnpg.io/cluster: postgres
        - podSelector:
            matchLabels:
              app: minio-bucket-job
      ports:
        - protocol: TCP
          port: 9000
