---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: app
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgCqq/cQj9Nnyvr+rhOGjqqQRjsv0gWQReNPyOJha+BC8IZovW33+D0aBxiuYRlslpxX0EihLGGASscJb6Ky2X7pV9GRZwcIag3L7+o4uDpvI6qfzjbJKpiXJDB+IujBjAffdQiwWoAp+XBb56HOA6lhZ0GOFnCjJdl5i5n6LnNuM5lu26yxVrOy+R/yVuwrjtRY+1xGUO68R3VTd1jqkwd2STaPdWdoN9RDS34AvDhw1CotDM0LlWQzk02/WnpM6zp+mj+ai6++mg91Y/3fDLZtDrVOGu7r0OpVl1WwHXgQvtnzvBM0G+IUaB3+tK1rZzzSKB0ehZUS++5VyZaxPdB266uSA+B6Zz5RCPpGE3P2M42jHkRWMPHjhqH82WwYH5PQ8t/GVur7Zvg15wIzCc/SO+xVFS6DVDGoKFuL4MWDKwu+BT/ar1W36aZYU0ImqmYlmM/6rolGy1c9WVO7BMwUDxAGg8CK9XgYICfnFcJuxJK+Fy4Lxp9Apo1m+HFepyj019v4yOTtUH7CK04TopHl/FiJEh3sh9xqevEmgfkqsYd+FwFoXs1nDXt18O8+R/t0A4Nn5Pis4K2Ja2QqmuypnbiAhj3bskEnvwlGVT7cOAsOgGr0TbKeGnkNkotqPO0gHTm9mN6ZtlS95DzOrdjAcXSIsosDJ/m6wsWHJpK0LB+Ub4JTqBXO1bHAKtWg/jL12jZiQNfdakjDeh046zz9Cu3o/kBLPa9SB7FVVw==
    MINIO_ROOT_USER: AgB+vIUugFYcB1CY31U9VpNER1LC9pWBE1kfQ2gSbavIFLjeCtbqb+31wScaEyEjFRaubL9eX+Dl5z1Yklt36zalU+KbA0t2XaemQ5AADCV9Fa2Eyc8jnGQGRhFbB+82tz27qGFwtK3o4Z++CLbJ8D7KfSlVpSHt1fjgsCh0fwtp021mfBCyEGpi4zG3sFWTDZfCEP64EC0TF8w+cKC5PZxf2YVwWPO3ErsEFOoxLmIBrtJpZVUq0YwD2eHKrFqYNG+VWUOQR89fgNqViKqI+pqtJH/Q0AayFsiwlDf0Ag+cBLamJtdxs5q10QoSehmge888v51nhFMLo4qglNV/IoTqe5OzlFE+o0vE05XDsOaUf2hCBdfddkNmEQiRclkYIcoLn82QBfxb1psZJs2Z7i6UkE9P330YEmv53/QKsoXP3LgT2UoUA6dgi4FtFR4mML2Dkio4/S1HIw840/tRHT0N+WvQYyNVzAYhkim1JzpWJARpRP4xENif15Xh9yUFqPk+q9fgm+DgTeRy/nwWo0x8NgTMYCi5WPOcY4F4osxTIbmCXrzO6GWwj87IB0leLPqfsYLRI9pXBDVk+1XX9BkNIAR2xU52unLDGepTjXMCXsgVwKzpXGyHGikG8pO7uP4dffW8WV634zectbYz9BQv7GvvnqTKefsvlQ8Srx8X7+Mpm3IkKCcMo3PrPkq23BnD2iN0rmuW3XJE
  template:
    metadata:
      name: minio-credentials
      namespace: app
